#!/bin/bash
# Set up wp-config.php.
# Requires WP-CLI
################################################################################
function configure_database() {
    echo -e ${YELLOW}
    echo -e "Configure the  new Database for WordPress."
    echo -e "A strong password will be automatically assigned for your admin"
    echo -e "user. You'll have access to this at the end of the config process."
    echo -e "Path: $WP_PATH"
    echo -e ${NC}

    # Create a 'random' 32 character password using printable posix characters.
    WP_PASS=$(random_password 32 alnum)
    echo -e "Enter a username. NOT 'ADMIN'!"
    read WP_USERNAME

    # Install WordPress
    wp core install --url=$WP_PATH --title="Basic Test Site" --admin_user=$WP_USERNAME --admin_password="${WP_PASS}" --admin_email=$EMAIL --allow-root

    # Install WordPress language
    wp language core install vi_VN --allow-root
    wp language core activate vi_VN --allow-root

    # Discourage search engines
    wp option update blog_public $SEARCH_ENGINES --allow-root

    # delete all pages, and create homepage, about page, contact page
    wp post delete $(wp post list --post_type='page' --format=ids --allow-root) --allow-root 
    wp post create --post_type=page --post_title=Home --post_status=publish --post_author=$(wp user get $WP_USERNAME --field=ID --allow-root) --allow-root
    wp post create --post_type=page --post_title=About --post_status=publish --post_author=$(wp user get $WP_USERNAME --field=ID --allow-root) --allow-root
    wp post create --post_type=page --post_title=Contact --post_status=publish --post_author=$(wp user get $WP_USERNAME --field=ID --allow-root) --allow-root

    # delete readme and license
    rm license.txt
    rm readme.html

    # set homepage as front page
    wp option update show_on_front 'page' --allow-root

    # set homepage to be the new page
    wp option update page_on_front $(wp post list --post_type=page --post_status=publish --posts_per_page=1 --pagename=home --field=ID --format=ids --allow-root) --allow-root

    # set pretty urls
    wp rewrite structure '/%postname%/' --hard --allow-root
    wp rewrite flush --hard --allow-root

    echo -e ${YELLOW}
    echo -e "WordPress has been installed successfully."
    echo -e ""
    echo -e "DB Info:"
    echo -e "DB Name: $DB_NAME"
    echo -e "DB User: $DB_USER"
    echo -e "DB Pass: $DB_PASS"
    echo -e ""
    echo -e "WordPress User details:"
    echo -e "WP username: $WP_USERNAME"
    echo -e "WP password: $WP_PASS"
    echo -e ${NC}
}
